In [2]:
import os
import random
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import linear_model
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression

from sklearn.base import TransformerMixin
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

import numpy as np
import copy
import hashlib
import json
import warnings
import calendar
import datetime
warnings.filterwarnings('ignore')
import pycountry_convert as cc

%matplotlib inline
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import MinMaxScaler


from sklearn.metrics import accuracy_score, precision_score, \
                            recall_score, f1_score, \
                            roc_auc_score, roc_curve

from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor,
    GradientBoostingClassifier,
    GradientBoostingRegressor,
)
from sklearn.metrics import mean_squared_error
from sklearn.tree import (
    DecisionTreeClassifier,
    DecisionTreeRegressor,
)
from math import log2

from utils.utils import process_categorical_features

from imblearn.over_sampling import SMOTE

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

In [3]:
df = pd.read_csv(os.path.join('data', 'train.csv')) 
df1=df.copy()
df1.info()
df1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 338487 entries, 0 to 338486
Data columns (total 12 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   id                                338487 non-null  int64
 1   user_address                      338487 non-null  object
 2   user_balance_usd                  338487 non-null  float64
 3   user_balance_coin_a               338487 non-null  float64
 4   user_historical_transactions_10s  338487 non-null  int64
 5   user_historical_transactions_30s  338487 non-null  int64
 6   exchange_a_price                  309845 non-null  float64
 7   exchange_b_price                  338487 non-null  float64
 8   exchange_a_volatility             323277 non-null  object
 9   exchange_b_volatility             330565 non-null  float64
 10  anonymous                         338487 non-null  object
 11  result                            338487 non-null  int64
dtypes: float64(5), int64(4), object(3)
memory usage: 31.0+ MB

,id,user_address,user_balance_usd,user_balance_coin_a,user_historical_transactions_10s,user_historical_transactions_30s,exchange_a_price,exchange_b_price,exchange_a_volatility,exchange_b_volatility,anonymous,result
0,8,0x930B,84139.092267,44.193560,0,0,66.742521,66.8325,very high,0.000367,A113,0
1,12,0x5779,34609.449276,331.501171,0,0,41.429574,41.5401,low,0.000695,M958,0
2,28,0x5779,30598.783296,1581.902691,0,0,35.817631,35.8701,very low,0.000431,F255,0
3,50,0x5779,20992.680359,1260.406181,0,0,47.711827,47.8233,low,0.000456,F2332,0
4,56,0xD47A,120838.946555,180.090128,0,0,52.812842,52.6869,low,NaN,A198,0
...,...,...,...,...,...,...,...,...,...,...,...,...
338482,3988947,0x5779,29374.263175,352.561329,0,0,46.680615,46.6683,medium,0.000435,M142,0
338483,3988948,0x5AEe,50847.577759,239.577796,0,0,72.139667,360.4125,low,0.000452,A131,0
338484,3988961,0x930B,121303.381921,160.222687,0,0,52.285416,52.3887,low,0.000285,A2158,0
338485,3988964,0x5779,18515.028195,1927.485662,0,0,38.559282,38.6211,very low,0.000185,F1831,0
338486,3988973,0x5779,21459.884902,526.017633,0,0,NaN,47.0295,low,0.000437,M1012,0

In [4]:
df.corr()

,id,user_balance_usd,user_balance_coin_a,user_historical_transactions_10s,user_historical_transactions_30s,exchange_a_price,exchange_b_price,exchange_b_volatility,result
id,1.000000,-0.000087,-0.000542,0.002663,0.002178,0.000967,-0.000016,0.002983,0.000897
user_balance_usd,-0.000087,1.000000,-0.587663,-0.031081,-0.048926,0.213988,0.080039,-0.085369,-0.018770
user_balance_coin_a,-0.000542,-0.587663,1.000000,0.018207,0.027556,-0.314347,-0.116180,0.035495,0.017267
user_historical_transactions_10s,0.002663,-0.031081,0.018207,1.000000,0.526806,0.034195,0.012404,0.155497,0.354665
user_historical_transactions_30s,0.002178,-0.048926,0.027556,0.526806,1.000000,0.085027,0.035226,0.242663,0.421841
exchange_a_price,0.000967,0.213988,-0.314347,0.034195,0.085027,1.000000,0.371172,0.038767,0.089232
exchange_b_price,-0.000016,0.080039,-0.116180,0.012404,0.035226,0.371172,1.000000,0.018454,0.036113
exchange_b_volatility,0.002983,-0.085369,0.035495,0.155497,0.242663,0.038767,0.018454,1.000000,0.198650
result,0.000897,-0.018770,0.017267,0.354665,0.421841,0.089232,0.036113,0.198650,1.000000

In [5]:
df.user_historical_transactions_30s.unique()

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
def meds (df):

    cats = ['very low', 'low', 'medium', 'high','very high']
    dic ={}
    for s in cats :
        dic[s]=0
        med = df.exchange_b_volatility[ df['exchange_a_volatility'] == s].mean()
        dic[s]=med
    avg =df.exchange_b_volatility[ df['exchange_a_volatility']!='Null'].mean()
    
    return dic, avg
dic , avg =meds(df)
avg

0.0004585502149546021

In [7]:
df.exchange_b_price.max()

488.3886

In [8]:
df.exchange_b_price.min()

31.0275

In [9]:
def clean_data (df):
    df1 = df.copy()
    
    
    
    df1['anonymousL'] = df1.anonymous.str.replace('\d','')
    df1['anonymousN'] =df1.anonymous.str.replace('[aA-zZ]+','') 
    
    df1['anonymousN']=df1['anonymousN'].astype('int64')
    
    df1['anonymousL']=df1['anonymousL'].astype('category')
    
    
    
    #df1['exchange_a_price'] = df1['exchange_a_price'].fillna(df.exchange_b_price)
    #df1['exchange_b_price'] = df1['exchange_b_price'].fillna(df.exchange_a_price)
    
    dic ,avg = meds(df1)
    df1['exchange_a_volatility']= df1['exchange_a_volatility'].map(dic)
    #df1['exchange_a_volatility']=df1['exchange_a_volatility'].astype('float64')
    
    #df1['exchange_a_volatility'] = df1['exchange_a_volatility'].fillna(avg)
    
    df1['profit'] = abs(df1.exchange_b_price - df1.exchange_a_price)
    
    
    robustscaler = RobustScaler()
    prof = df1[['profit']]
    robustscaler.fit(prof)
    df1['profit'] = robustscaler.transform(prof)
    
    bal_c = df1[['user_balance_coin_a']]
    robustscaler.fit(bal_c)
    df1['user_balance_coin_a'] = robustscaler.transform(bal_c)
    
    
    
    bal_u = df1[['user_balance_usd']]
    robustscaler.fit(bal_u)
    df1['user_balance_usd'] = robustscaler.transform(bal_u)
    
    

    df_=df1.dropna()
    #df1['exchange_a_volatility'] = df1['exchange_a_volatility'].astype('float')
    #df1['exchange_a_price'] = df1['exchange_a_price'].fillna(df.exchange_b_price)
    #df1['exchange_b_price'] = df1['exchange_b_price'].fillna(df.exchange_a_price)
    
    
    #df_ = df1[['user_balance_usd', 'user_balance_coin_a', 'user_historical_transactions_10s', 'user_historical_transactions_30s', 'exchange_a_price', 'exchange_b_price' , 'exchange_a_volatility','exchange_b_volatility','result','profit','anonymousN','anonymousL']].copy()
    #df_ = df1[['user_balance_usd', 'user_balance_coin_a', 'user_historical_transactions_10s', 'user_historical_transactions_30s' , 'exchange_a_volatility','exchange_b_volatility','result','profit']].copy()
    #df_["anonymous"] =df_["anonymous"].astype("category")
    #df_ = df1[['profit', 'user_balance_coin_a', 'user_historical_transactions_30s', 'user_historical_transactions_30s','result']].copy()
    #df_ =df1[['user_historical_transactions_10s','user_historical_transactions_30s','profit','user_balance_coin_a','result','exchange_a_volatility','exchange_b_volatility','anonymousL']]
    
    #df1=df1.dropna()
    
    #df_= df1[['profit','exchange_a_volatility','user_balance_coin_a','user_balance_usd','user_historical_transactions_30s','result']].copy()
    #df_= df1[['profit','exchange_a_volatility','user_balance_coin_a','user_balance_usd','exchange_a_price','result']].copy()

    
   
    #df_= df_.drop('anonymous',axis=1)
    #df_= df_.drop('id',axis=1)
    #df_ = df1.copy()
    
    
    #df_ =convert_categorical_features(df_)
    
    #df_= convert(df_)
    
    return df_

In [10]:
def encode_binary_field(f):

    f_e = f.copy()
    
    ## create a dictionary mapping the current values to int values
    enconding_map = {'very low' : 0 , 'low':1, 'medium':2, 'high':3,'very high':4}
    ## change target using the mapping
    f_e = f_e.map(enconding_map)
   
    
    return f_e

In [11]:
def convert_categorical_features(X, ordinal_feat='exchange_a_volatility'):

    X_s = X.copy()
    
    
    ## create list of ordered categories for ordinal feature
    ordered_cats = ['very low', 'low', 'medium', 'high','very high']
    #ordered_cats = [0,1,2,3,4]
    ## convert ordinal feature to dtype 'category'
    X_s[ordinal_feat] = X_s[ordinal_feat].astype('category')
    
    
    ## Assign natural order to ordinal feature
    X_s[ordinal_feat] =X_s[ordinal_feat].cat.set_categories(ordered_cats, ordered=True)
    
    #X_s['exchange_a_volatility'] = encode_binary_field(X_s['exchange_a_volatility'] )
    
    

    return X_s

In [12]:

def convert (X , column = 'exchange_b_volatility'):

    X_a = X.copy()
    
    X_a['exchange_b_volatility'] =pd.cut(X_a['exchange_b_volatility'] , 5, labels =['very low', 'low', 'medium', 'high','very high']   )
    
    X_a['exchange_b_volatility'] = encode_binary_field(X_a['exchange_b_volatility'] )
   
    
    return X_a

In [13]:
df_clean = clean_data(df)

In [ ]:
#from imblearn.over_sampling import SMOTE
df_tree= df_clean.copy()
X = df_tree.drop('result',axis=1)
y = df_tree['result']
X_ = process_categorical_features(X)



X_train, X_test, y_train, y_test = train_test_split(
        X_, y, random_state=42, test_size=0.20)  


sm = SMOTE(random_state = 42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train.ravel())

In [ ]:
clf = GradientBoostingClassifier()

In [ ]:
clf.fit(X_train_res,y_train_res)
predicted_proba= clf.predict_proba(X_test)
y_pred =clf.predict(X_test)
roc_auc = roc_auc_score(y_score=predicted_proba[:,1], y_true= y_test)
   
#confmat = confusion_matrix(y_true=y_test, y_pred=x1)
print('The AUROC of our classifier is = %.3f' % roc_auc)

feature_importances = pd.Series(data=clf.feature_importances_, index=X_.columns)
feature_importances.sort_values(ascending=False)

In [ ]:
#feature_importances = pd.Series(data=clf.feature_importances_, index=X_.columns)
#feature_importances.sort_values(ascending=False)

In [ ]:
y_pred =clf.predict(X_test)


cm = confusion_matrix(y_test, y_pred, labels=clf.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=clf.classes_)
disp.plot();